# Generated by Django 3.2.6 on 2021-08-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar_images/dummy-avatar.jpg', null=True, upload_to='user_avatar_images'),
        ),
    ]
